### ISSUE TITLE
Web Pages of other host is down

### ISSUE THREAD

**Issue by abt2804** [Fraizeraust/reactos-testing-contest#4]
The web pages of other host (which is Mcpg server) is no more
Probably he deleted his files by a reason or accidentally? I don't know. Please ask him about this server.
Web pages which got affected - 
http://mcpg.pl/archive/rosdiscord/01092018/dark/ReactOSCommunity_3rd-contest-entries.html
http://mcpg.pl/archive/rosdiscord/01092018/dark/ReactOSCommunity_4th-contest-entries.html

**Comment by GeoB99** [comment]
I'm aware of this and the dead links have been removed in this commit - [`47b9380`](https://github.com/Fraizeraust/reactos-testing-contest/commit/47b938028fcaca273abdb689b721a9a3525fd883). What is needed is for @cernodile updating the VPS' contents with the latest committed changes.

I've asked Mcpg about this and he said he's removed the access to these links. I am not responsible for his host therefor I cannot estimate when this problem will be fixed. I'll bring the links back once the page links are alive again.

**Comment by abt2804** [comment]
Alright.

**Comment by GeoB99** [comment]
Mcpg restored access to archive entry pages. The links are now back in [`74674bd`](https://github.com/Fraizeraust/reactos-testing-contest/commit/74674bd509fdcd993723fbaec03d5c0092ee1d80).
